### PR TITLE
fix: improve live region behavior for screen readers

### LINKED ISSUE #2412: fix: 🤔 Carousel's live region behavior is not properly implemented
## Current behavior
The carousel's live region behavior is not properly implemented

## Expected behavior
When automatic rotation is turned off, the carousel slide content is included in a live region. This makes it easier for screen reader users to scan through the carousel slides. When screen reader users activate the next or previous slide button, the new slide content is announced, giving users immediate feedback that helps them determine whether or not to interact with the content. Very importantly, if automatic rotation is turned on, the live region is disabled. If it were not, the page would become unusable as announcements of the continuously changing content constantly interrupt anything else the user is reading.

## Steps to reproduce
Navigate to the carousel with the screen reader active

Test with automatic rotation OFF:
- Use next/previous buttons
- Verify new slide content is announced

Test with automatic rotation ON:
- Verify slides change without announcements
- Attempt to read other page content while carousel rotates

## Technical Information
This is an accessibility issue related

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

### LINKED ISSUE #2460: fix: 🤔 focus inside carousel not preventing auto scroll
## Current behavior
The carousel's auto-scrolling only stops when the entire carousel component has focus. When navigating within a slide (e.g., focusing on interactive elements), auto-scrolling continues to run. After a few seconds, the current slide scrolls out of view, making it impossible to interact with the slide content, and focus gets reset back to the carousel component.

## Expected behavior
Auto-scrolling should pause/stop when any interactive element within a slide receives focus, not just when the carousel container itself is focused. The auto-scrolling should remain paused as long as the user is interacting with content inside any slide, and focus should remain on the interactive element the user was engaging with.

## Steps to reproduce
Open this [page](https://www.union-investment.de/unsere-services/medien) and check the carousel focus behaviour.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

### PR DESCRIPTION
**Pull request by balco0110**
## Description:

Closes: https://github.com/solid-design-system/solid/issues/2412 and https://github.com/solid-design-system/solid/issues/2460
## Definition of Reviewable:

- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/carousel/carousel.ts [hunk 1]
```diff
@@ -754,8 +782,6 @@ export default class SdCarousel extends SolidElement {
               aria-label="${this.localize.term('nextSlide')}"
               aria-controls="scroll-container"
               aria-disabled="${nextEnabled ? 'false' : 'true'}"
-              @focus=${this.handleFocus}
-              @blur=${this.handleBlur}
```
Comment (auroraVasconcelos) [inline packages/components/src/components/carousel/carousel.ts:758]: Is this not necessary anymore?

Comment (balco0110) [reply packages/components/src/components/carousel/carousel.ts:758]: The @focus/@blur on the buttons were removed because focus tracking was moved to the component level using focusin/focusout in connectedCallback. This captures focus from any element inside the carousel (not just nav buttons), which is needed to correctly pause autoplay and silence the live region whenever the user interacts with any part of the carousel.

File: .changeset/wacky-canyons-scream.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+Fix `sd-carousel` live region behavior for screen readers and focus not preventing auto scroll
```
Comment (smfonseca) [inline .changeset/wacky-canyons-scream.md]:
```suggestion
Fixed `sd-carousel` live region behavior for screen readers and focus not preventing auto scroll
```

File: packages/components/src/components/carousel/carousel.ts [hunk 3]
```diff
@@ -557,18 +592,13 @@ export default class SdCarousel extends SolidElement {
     const slides = this.getSlides();
     const slidesWithClones = this.getSlides({ excludeClones: false });
 
-    // Sets the next index without taking into account clones, if any.
```
Comment (smfonseca) [inline packages/components/src/components/carousel/carousel.ts:560]: Can you please re-add the comments? Not sure why they were removed.

File: packages/components/src/components/carousel/carousel.ts [hunk 4]
```diff
@@ -557,18 +592,13 @@ export default class SdCarousel extends SolidElement {
...
-    // Inconsistencies may arise when scrolling from the last slide if slidesPerMove is not divisible by the slide count.
-    // This is most apparent with slidesPerPage set to one, but we won't provide a fix as it's not a recommended use case anyways.
     const newActiveSlide = (index + slides.length) % slides.length;
     this.activeSlide = newActiveSlide;
 
     if (fade) {
       return;
     }
 
-    // Get the index of the next slide. For looping carousel it adds `slidesPerPage`
```
Comment (smfonseca) [inline packages/components/src/components/carousel/carousel.ts:570]: Please re-add comments.

**Review by smfonseca — COMMENTED** [review]
I think it makes sense to create a follow up ticket for the `auto-play` button announcements. From my perspective, the user should get announcements when starting and pausing the carousel (when a action is performed).

File: packages/components/src/components/carousel/carousel.ts (hunk 3 above)
Comment (balco0110) [reply packages/components/src/components/carousel/carousel.ts:560]: i've reverted the changes

File: packages/components/src/components/carousel/carousel.ts (hunk 4 above)
Comment (balco0110) [reply packages/components/src/components/carousel/carousel.ts:570]: i've reverted the changes

**Review by smfonseca — APPROVED** [review]
@balco0110 please keep in mind to create a follow-up ticket for the `auto-play` button announcements
