### PR TITLE
fix: 🤔 sd-brandshape – improve image positioning

### LINKED ISSUE #1242: fix: 🤔 sd-brandshape – scale placeholder image proportionally
## Current behavior
Component shows a distorted placeholder image

Image

## Expected behavior
The placeholder icon in the placeholder image is shown 1:1 and not distorted.
Figma Link: https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=8713-2940&t=9j5W6Vvj2CwLpBA2-0
Image

## Steps to reproduce
Open link: 
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-brandshape--variants

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:

Closes #1242.

## Definition of Reviewable:

- [x] E2E tests (features, a11y, bug fixes) are created/updated - (screenshot tests capture this change)
- [x] relevant tickets are linked

### CODE REVIEW

**Comment by smfonseca** [comment]
@Vahid1919 I think the issue is deeper than just adjusting the template. The fix needs to be done in the style of the image variant, otherwise everytime someone uses this variant, the image will need to be adjusted

**Comment by Vahid1919** [comment]
@smfonseca @mariohamann I added some extra breakpoints to keep our placeholder centred across more sizes (eg: previous ones did not look good on my monitor vs laptop screen). I didn't feel super happy with the solution, so open to any other suggestions if you have them :)

**Comment by MartaPintoTeixeira** [comment]
Please vertically align the image icon in different breakpoints.

File: packages/components/src/components/brandshape/brandshape.ts [hunk 1]
```diff
@@ -22,6 +22,8 @@ type Breakpoints = 0 | 414 | 640;
  * @csspart shape-top - Top shape.
  * @csspart shape-middle - Middle shape.
  * @csspart shape-bottom - Bottom shape.
+ *
+ * @cssproperty --image-translate-Y - The Y translation of the image slot. Adjust this based on your media queries or breakpoints to achieve the desired effect.
```
Comment (karlbaumhauer) [inline packages/components/src/components/brandshape/brandshape.ts:26]:
```suggestion
 * @cssproperty --image-translate-Y - The Y translation of the image slot. Adjust this based on your media queries or breakpoints to correct possible misplacement of the image.
```

**Review by karlbaumhauer — APPROVED** [review]
approved with a small text suggestion.

**Comment by Vahid1919** [comment]
@MartaPintoTeixeira I have updated the alignment to work with the breakpoints specified in the screenshots. Please review.

**Comment by mariohamann** [comment]
Please improve the title so that is more understood for developers what they can expect here.

**Comment by Vahid1919** [comment]
@mariohamann title is updated :)

**Comment by mariohamann** [comment]
I've rewritten the whole logic of how size and image of image, wrapper and border are calculated.
- Now every image, despite of its (1.) orientation (square, landscape, portrait), (2.) the size of the component and (3.) its content is always in the middle. <video src="https://github.com/user-attachments/assets/e34296fb-ef79-4105-8627-cdcf86fc76ec">
- This  was adapted to the border and image style, which now fit a lot better when switching between variants. <video src="https://github.com/user-attachments/assets/0ac8594f-d9ae-4625-9822-88a74228801b" />

**Comment by MartaPintoTeixeira** [comment]
Looking good Mario. thanks!

**Review by MartaPintoTeixeira — APPROVED** [review]

**Review by yoezlem — APPROVED** [review]

File: packages/components/src/components/brandshape/brandshape.stories.ts [hunk 2]
```diff
@@ -125,4 +125,23 @@ export const Shapes = {
...
+
+export const ImageTranslateY = {
+  name: 'Image Translation',
+  render: () => html`
+    <sd-brandshape variant="image">
+      <div class="slot slot--border slot--text h-8 w-full">Default slot</div>
+      <img
+        slot="image"
+        src="./placeholders/images/architecture.jpg"
+        style="object-position: top right"
```
Comment (smfonseca) [inline packages/components/src/components/brandshape/brandshape.stories.ts:140]: NIT: instead of setting the style inline, I think you could use a tailwind class `object-right-top`

**Review by smfonseca — APPROVED** [review]
🥇

File: packages/components/src/components/brandshape/brandshape.stories.ts (hunk 2 above)
Comment (Vahid1919) [reply packages/components/src/components/brandshape/brandshape.stories.ts:145]: I think the idea in this story specifically was to highlight the usage of the object-position style.
