### PR TITLE
fix: 🤔 update experimental status

### LINKED ISSUE #1209: fix: 🤔 update experimental status
## Current behavior
The `sd-list` component still has `status: experimental` in the docs and the components `sd-tab-group` and `sd-link` are missing the status at all.
## Expected behavior
All 3 components are set to `status: stable` with the correct version number since they are stable being added.
## Technical Information
The git-file-history needs to be inspected in order to find the version number since which they are stable. If the correct version number is not easily to be found, the last iteration on the component should be used as "stable".
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:

Closes #1209.
 
I did not change the "since" version number as we did not make any changes in the component. Please let me know if I should change it to our current version.

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] relevant tickets are linked

### CODE REVIEW

**Review by smfonseca — APPROVED** [review]

**Review by yoezlem — APPROVED** [review]

File: packages/components/src/components/link/link.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import SolidElement from '../../internal/solid-element';
 /**
  * @summary A link component.
  * @documentation https://solid.union-investment.com/[storybook-link]/link
- * @status experimental
+ * @status stable
  * @since 1.2
```
Comment (karlbaumhauer) [inline packages/components/src/components/link/link.ts:13]: looking at our changelog, its stable since our init of the components => Verison 1.0.0

File: packages/components/src/styles/hidden-links/hidden-links.declaration.ts [hunk 2]
```diff
@@ -3,7 +3,7 @@ import type { Style } from '../../declaration';
 export default {
   styleName: 'sd-hidden-links',
   summary: 'Hidden links can be used to show links only for keyboard users.',
-  status: 'experimental',
+  status: 'stable',
```
Comment (karlbaumhauer) [inline packages/components/src/styles/hidden-links/hidden-links.declaration.ts:6]: looking at our changelog it has been added in version 3.15.0

File: packages/components/src/styles/hidden-links/hidden-links.declaration.ts [hunk 3]
```diff
@@ -3,7 +3,7 @@ import type { Style } from '../../declaration';
...
   since: '3.12.0',
```
Comment (karlbaumhauer) [inline packages/components/src/styles/hidden-links/hidden-links.declaration.ts:7]:
```suggestion
  since: '3.15.0',
```

File: packages/components/src/styles/list/list.declaration.ts [hunk 4]
```diff
@@ -3,7 +3,7 @@ import type { Style } from '../../declaration';
 export default {
   styleName: 'sd-list',
   summary: 'Generates basic styles for list elements.',
-  status: 'experimental',
+  status: 'stable',
   since: '1.33.1',
```
Comment (karlbaumhauer) [inline packages/components/src/styles/list/list.declaration.ts:7]: looking at our changelog it has been added in version 1.39.0

**Review by karlbaumhauer — CHANGES_REQUESTED** [review]
I don't want to be picky but if we use the status, the version should be correct... ;-)

**Review by karlbaumhauer — APPROVED** [review]
