### PR TITLE
fix: added accessible names for start/stop autoplay button

### LINKED ISSUE #2414: fix: 🤔 Accesible names for start/stop autoplay button
## Current behavior
The carousel rotation control button does not have proper accessible names that indicate the current state of the carousel:

When the carousel is rotating, the button lacks "Stop Automatic Slide Show" accessible name
When the carousel is not rotating, the button lacks "Start Automatic Slide Show" accessible name

## Expected behavior
The rotation control button should have dynamic accessible names that communicate both the current state and available action:

If the carousel is rotating, the button's accessible name should be "Stop Automatic Slide Show"
If the carousel is not rotating, the accessible name should be "Start Automatic Slide Show"
This informs screen reader users about the current carousel state and what action the button will perform.

## Steps to reproduce
Navigate to a page with the carousel component
Use a screen reader or inspect the button with developer tools
Check the accessible name (aria-label, aria-labelledby, or button text content)
Toggle the carousel play/pause state
Verify that the accessible name updates to reflect the new state

## Technical Information
This is an accessibility issue related

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

### PR DESCRIPTION
**Pull request by balco0110**
## Description:

Closes: https://github.com/solid-design-system/solid/issues/2414
## Definition of Reviewable:

- [x] E2E tests (features, a11y, bug fixes) are created/updated

- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/translations/de.ts [hunk 1]
```diff
@@ -68,7 +68,9 @@ const translation: Translation = {
   showMore: 'Mehr anzeigen',
   showPassword: 'Passwort anzeigen',
   slideNum: (slide, count) => `Folie ${slide} von ${count}`,
+  startAutoplay: 'Automatische Diashow started',
```
Comment (mariohamann) [inline packages/components/src/translations/de.ts]: "Diashow" feels weird. Please clarify with German speaking UX.

File: packages/components/src/translations/en.ts [hunk 2]
```diff
@@ -68,7 +68,9 @@ const translation: Translation = {
   showMore: 'Show more',
   showPassword: 'Show password',
   slideNum: num => `Slide ${num}`,
+  startAutoplay: 'Start Automatic Slide Show',
   startDateSelected: 'Start date selected',
+  stopAutoplay: 'Stop Automatic Slide Show',
```
Comment (mariohamann) [inline packages/components/src/translations/en.ts]: "Slide show" is really image focused. Pelase clarify.

File: packages/components/src/translations/de.ts (hunk 1 above)
Comment (balco0110) [reply packages/components/src/translations/de.ts]: I've alerady contacted Carina, she will test this and let me know

Comment (mariohamann) [reply packages/components/src/translations/de.ts]: It's less about testing but providing proper wording

Comment (balco0110) [reply packages/components/src/translations/de.ts]: i wrote to Carina and waiting  for an anwer

File: .changeset/slick-lands-fail.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+Added accesible names for start/stop autoplay button in `sd-carousel`
```
Comment (smfonseca) [inline .changeset/slick-lands-fail.md]:
```suggestion
Added accessible names for `start`/`stop` autoplay button in `sd-carousel`
```

File: packages/components/src/translations/en.ts (hunk 2 above)
Comment (smfonseca) [reply packages/components/src/translations/en.ts]: I suggest using something like `Start automatic playback`. 
What do you guys think?

File: packages/components/src/components/carousel/carousel.ts [hunk 4]
```diff
@@ -337,10 +337,8 @@ export default class SdCarousel extends SolidElement {
   handlePausedAutoplay() {
     if (this.pausedAutoplay) {
       this.autoplayController.stop();
-      this.autoplayControls?.setAttribute('aria-pressed', 'false');
```
Comment (smfonseca) [inline packages/components/src/components/carousel/carousel.ts:367]: Removing `aria-pressed` decreases accessibility, I believe we should keep it. Can you double-check if we are able to use it?

File: packages/components/src/translations/de.ts (hunk 1 above)
Comment (balco0110) [reply packages/components/src/translations/de.ts]: I got answer from Carina to change it to "Automatische Wiedergabe stoppen" and "Automatische Wiedergabe starten"

File: packages/components/src/translations/en.ts (hunk 2 above)
Comment (balco0110) [reply packages/components/src/translations/en.ts]: i asked Carina about this she said it is ok like this on english, but the german translation is actually this "start automatic playback", and for me "start/stop automatic playback" sounds better.

File: packages/components/src/components/carousel/carousel.ts (hunk 4 above)
Comment (balco0110) [reply packages/components/src/components/carousel/carousel.ts:367]: i've added back the aria-pressed as true

**Review by smfonseca — DISMISSED** [review]

**Review by smfonseca — APPROVED** [review]

**Review by MartaPintoTeixeira — APPROVED** [review]
