### PR TITLE
fix: disable sd-tab-group buttons on scroll limits

### LINKED ISSUE #955: fix: 🤔 disable navigation buttons on sd-tab-group when scrolling reaches end points
## Current Behavior:
The navigation buttons remain active regardless of the scroll position, which may confuse users when no more tabs are available in the direction they wish to scroll.

Image

## Expected Behavior:
The navigation button on the side of the reached end should be disabled when the user cannot scroll further in that direction.

Image

[Figma link here.](https://www.figma.com/file/Vpeho2Pr6TcBlwuczwAc5S/sd-tab-V.1.0.0?type=design&node-id=17853-6228&mode=design&t=WnGLKLoCVSNEtU6b-4)

## Technical Information
Maybe the functionality from sd-scrollable and/or sd-carousel can help.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by paulovareiro29**
## Description:

Closes #955 

## Definition of Reviewable:
- [x] E2E tests (features, a11y, bug fixes) are created/updated
- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/tab-group/tab-group.ts [hunk 1]
```diff
@@ -92,6 +98,8 @@ export default class SdTabGroup extends SolidElement {
       this.syncTabsAndPanels();
       this.mutationObserver.observe(this, { attributes: true, childList: true, subtree: true });
       this.resizeObserver.observe(this.nav);
+      this.handleScroll();
+      this.nav.addEventListener('scroll', () => this.handleScroll());
```
Comment (smfonseca) [inline packages/components/src/components/tab-group/tab-group.ts:103]: What do you think about debouncing this event?

**Review by smfonseca — APPROVED** [review]
