### PR TITLE
fix: sd-navigation-item a11y reaudit

### LINKED ISSUE #2055: feat[dev]: ✨ implement A11y re-improvements to sd-navigation-item
## Description
This tasks describes the Figma implementation for: #2048 

This task describes the Storybook implementation for the sd-navigation-item component as part of the A11y re-improvements outlined in Epic #2048.

A11y improvements for sd-button can be found here: [sd-navigation-item Notes](https://www.notion.so/matuzo/sd-navigation-item-1baf3f6e1bc081ef8b6de2492a9cf6f3).

------------------------------------------

## New Comment
**Problem:** The accessible name of the button in the “separated” example is "toggle-details".
**Solution:** Provide a label that describes the button's purpose.

## New Notes
- `aria-controls` on the details element is not necessary.

## Notes

- Disabled navigation items: See [[sd-button](https://www.notion.so/sd-button-1baf3f6e1bc08198a2d6ddf4df8b1e21?pvs=21)](https://www.notion.so/sd-button-1baf3f6e1bc08198a2d6ddf4df8b1e21?pvs=21) . Everything I wrote there about disabling form elements applies here as well.

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by paulovareiro29**
## Description:

Closes #2055 

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/translations/de.ts [hunk 1]
```diff
@@ -49,7 +49,9 @@ const translation: Translation = {
   tagsSelected: 'Optionen ausgewählt',
   toggleColorFormat: 'Farbformat umschalten',
   transcriptIsOpen: 'Transkript ist offen',
-  unmute: 'Unmute'
+  unmute: 'Unmute',
+  expandNavigationItem: 'Navigationspunkt erweitern',
```
Comment (smfonseca) [inline packages/components/src/translations/de.ts:53]: Please sort alphabetically in the appropriate places

**Review by smfonseca — APPROVED** [review]
