### PR TITLE
fix: 🐛 sd-audio a11y and other things

### LINKED ISSUE #2066: feat[dev]: ✨ implement A11y Re-Improvements to sd-audio
## Description
This tasks describes the Figma implementation for: #2048 

This task describes the Storybook implementation for the sd-audio component as part of the A11y re-improvements outlined in Epic #2048.

A11y improvements for sd-audio can be found here: [sd-audio Notes](https://www.notion.so/matuzo/sd-audio-1baf3f6e1bc0808dba0bd2aadb5a18bb).

------------------------------------------

## Comment
**Problem:** The label of the “Playback Speed” button is always “Playback Speed”. There’s no indication at which speed it’s playing.
**Solution:** Consider updating the label accordingly, “Playback Speed 2x”, etc.

---

**Problem:** When you press the “Open transcript” button, focus moves to the drawer. When you close it, it doesn’t move back.
**Solution:** Manage focus.

## Note
- Consider listening to the reduced motion media feature to pause the animation.
- Inverted example: According to the WCAG contrast algorithm, the contrast ratio is high enough, but the algorithm isn't perfect, which can be seen here. The ratio is 4.73:1, but the text is still hard to read.

## Accessibility Information
- Provide audio descriptions to ensure all users can access the content.
**I wouldn’t know what to do here. You’re not talking about the transcript because there is another point that addresses transcripts. What do you mean by “audio descriptions”. Descriptions of sounds and background noises? If yes, explain what “ensure all users can access the content.” means.**
- Ensure all player controls (play, pause, volume, speed, etc.) are fully operable using only the keyboard.
**Isn’t that something the component already does for me?**

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by mariohamann**
Closes #2066 

- Improve focus management for elements within ShadowDOMs triggering sd-dialog and sd-drawer.
- Ensure sd-input supports password autofill.
- Update the type of the containingElement property in sd-dropdown.
- Fix component dependencies, so that needed components are automatically imported.
- Adjust aria-label for playback speed to reflect the current speed value.

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] E2E tests (features, a11y, bug fixes) are created/updated

- [x] relevant tickets are linked

### CODE REVIEW

**Comment by mariohamann** [comment]
@yoezlem As I fixed some other things on my way, I added two additional Story Points.

**Comment by paulovareiro29** [comment]
FYI: Edited PR description to automatically close the sd-audio ticket

File: packages/components/src/components/tooltip/tooltip.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import '../popup/popup';
```
Comment (paulovareiro29) [inline packages/components/src/components/tooltip/tooltip.ts:1]: Isn't the popup import needed? Since it is a dependency as well

File: .changeset/three-roses-agree.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+make sd-input compatible to autofill with passwords
```
Comment (paulovareiro29) [inline .changeset/three-roses-agree.md:5]:
```suggestion
Make sd-input compatible to autofill with passwords
```

File: .changeset/true-peas-pump.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+fix: trigger elements inside ShadowDOMs are correctly re-focused when sd-drawer or sd-dialog closes
```
Comment (paulovareiro29) [inline .changeset/true-peas-pump.md:5]:
```suggestion
Improved `sd-drawer` and `sd-dialog` focus management by ensuring trigger elements inside shadow DOMs are correctly re-focused when element closes.
```

File: .changeset/silly-gifts-cut.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+components that are needed in other components are now properly imported (e. g. sd-icon inside sd-button)
```
Comment (paulovareiro29) [inline .changeset/silly-gifts-cut.md:5]:
```suggestion
Component dependencies are not correctly imported (e.g. `sd-icon` inside `sd-button`)
```

File: .changeset/rare-mice-boil.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+fix: change type of containingElement property in sd-dropdown
```
Comment (paulovareiro29) [inline .changeset/rare-mice-boil.md:5]:
```suggestion
Adjusted type of `containingElement` property in `sd-dropdown`
```

File: .changeset/fine-planets-study.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+fix: update aria-label in sd-audio for playback speed to include current speed value
```
Comment (paulovareiro29) [inline .changeset/fine-planets-study.md:5]:
```suggestion
Improved `sd-audio` `aria-label` by including current speed value on playback speed button.
```

File: .changeset/three-roses-agree.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+Make sd-input compatible to autofill with passwords
```
Comment (smfonseca) [inline .changeset/three-roses-agree.md:5]:
```suggestion
Make `sd-input` compatible to autofill with passwords
```

**Review by smfonseca — DISMISSED** [review]

File: packages/components/src/components/tooltip/tooltip.ts (hunk 1 above)
Comment (mariohamann) [reply packages/components/src/components/tooltip/tooltip.ts:1]: Yes. I imported it like that (red), but linting always rewrite to just use the type. WTF.

CleanShot 2025-04-15 at 13 52 27@2x

**Review by paulovareiro29 — APPROVED** [review]
LGTM
