### PR TITLE
fix: improve sd-accordion and sd-quickfact a11y

### LINKED ISSUE #1496: feat[dev]: ✨ implement A11y improvements to sd-accordion and sd-accordion-group
## Description
This task describes the Storybook implementation for the sd-accordion and sd-accordion-group component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-accordion and sd-accordion-group can be found here: [sd-accordion and sd-accordion-group Notes](https://www.notion.so/matuzo/sd-accordion-sd-accordion-group-3ee7bfd705354e1e869ab477018a8225).

----------------------------------------

## Comment
No critical issues found.

## Notes

- Many implementations of accordions use headings (h2 or h3) with nested buttons instead of the header element for the accordion header because headings provide a convenient additional way of navigation for screen reader users. 
There is an example where you slot an h4, but this heading ends up nested inside a button, which means that the heading is not discoverable in some screen readers. The other way around, it works fine.

```
<h4><button>heading</button></h4> <!-- good -->
<button><h4>heading</h4></button> <!-- bad -->
```

- Instead of changing the role of the header element to button and adding tabindex, consider using an actual button element to decrease complexity.
- Each content slot is a named region. That's generally fine, but on a page with many accordion items (e.g., a FAQ page) where most or all of them are expanded, having too many landmarks can pollute landmark navigation.

## Best Practices
- Hiding content can become a potential barrier, making content more challenging to discover. Use this pattern only for non-critical information.

## Additional resources
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

## Suggested Solution
- [ ] switch from current implementation to using summary / details in the accordion and see how many issues will be solved/covered.
- [ ] open up a new ticket and define open todos/issue.
- [ ] check and fix #1500 

## Technical information
- shoelace already switched to summary/details. See there for more information and tests.
- don't forget to check the animation!

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by paulovareiro29**
## Description:
Closes #1496 #1500

This PR addresses:
- Adapt sd-accordion HTML using `details` and `summary` elements
- Adapt expandable sd-quickfact HTML using `details` and `summary` elements 

## Definition of Reviewable:

- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/quickfact/quickfact.ts [hunk 1]
```diff
@@ -27,56 +26,74 @@ export default class SdQuickfact extends SdAccordion {
...
-          tabindex=${this.expandable ? '0' : '-1'}
-          @click=${this.expandable ? this.handleSummaryClick : null}
-          @keydown=${this.expandable ? this.handleSummaryKeyDown : null}
-        >
-          <div
-            part="icon"
-            class=${cx('flex flex-grow-0 flex-shrink-0 flex-auto items-center', !this.expandable && 'cursor-default')}
-          >
-            <slot name="icon"></slot>
+    return this.expandable
```
Comment (smfonseca) [inline packages/components/src/components/quickfact/quickfact.ts:29]: Instead of repeating most of the markup, I think we could follow a similar strategy to what we did in the [map marker](https://github.com/solid-design-system/solid/blob/next/packages/components/src/components/map-marker/map-marker.ts#L75), step, button.. There may be some other parts that need to be updated but overall I guess it should work.

File: packages/components/src/components/accordion/accordion.ts [hunk 2]
```diff
@@ -61,9 +63,28 @@ export default class SdAccordion extends SolidElement {
...
+        if (change.type === 'attributes' && change.attributeName === 'open') {
+          if (this.accordion.open) {
+            this.show();
+          } else {
+            this.hide();
+          }
+        }
+      }
+    });
+    this.accordionObserver.observe(this.accordion, { attributes: true });
```
Comment (smfonseca) [inline packages/components/src/components/accordion/accordion.ts:82]: We should disconnect the observer on `disconnectedCallback`, or do you see any reason not to?

**Review by MartaPintoTeixeira — APPROVED** [review]

File: packages/components/src/components/quickfact/quickfact.ts (hunk 1 above)
Comment (paulovareiro29) [reply packages/components/src/components/quickfact/quickfact.ts:29]: Great hint, thanks!

File: packages/components/src/components/accordion/accordion.ts (hunk 2 above)
Comment (paulovareiro29) [reply packages/components/src/components/accordion/accordion.ts:83]: No reason not to. Added it

**Review by smfonseca — APPROVED** [review]

**Review by MartaPintoTeixeira — APPROVED** [review]

File: .changeset/beige-tools-camp.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@solid-design-system/components': patch
+---
+
+Adapt `sd-accordion` and expandable `sd-quickfact` HTML to use `<details />` and `<summary />` elements.
```
Comment (mariohamann) [inline .changeset/beige-tools-camp.md:5]: I personally would even say that this is a feature as this enhances UX a lot (e. g. searchability with the browser search tool so that accordions automatically open.)

**Review by mariohamann — DISMISSED** [review]

**Review by mariohamann — APPROVED** [review]
