### PR TITLE
fix: dot controls in sd-carousel behave like numbered controls

### LINKED ISSUE #1398: fix: 🤔 wrong behavior in dot-controls of `sd-carousel`
## Current behavior
Consider the following setup:
variant: dot, slides-per-page: 4, slides-per-move: 1.
Clicking the arrows is working fine, but directly clicking the bullets leads to the wrong positions in some sliders. In the screenshot, you can see that the 2nd dot is clicked, but the last one is shown as active.
Image

## Expected behavior
dot controls works same as number controls.
## Steps to reproduce
see above
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by StefanCikarevic**
## Description:
closes #1398 

## Definition of Reviewable:
- [x] E2E tests (features, a11y, bug fixes) are created/updated
- [x] relevant tickets are linked

### CODE REVIEW

**Comment by smfonseca** [comment]
@StefanCikarevic could you please add a test for this fix? Thank you

File: packages/components/src/components/carousel/carousel.ts [hunk 1]
```diff
@@ -457,7 +457,7 @@ export default class SdCarousel extends SolidElement {
   }
 
   render() {
-    const { scrollController, slidesPerPage } = this;
+    const { scrollController, slidesPerMove } = this;
```
Comment (karlbaumhauer) [inline packages/components/src/components/carousel/carousel.ts:460]: @Vahid1919 was this a leftover from the last change or did we explicitly renamed it? I got a bit lost on the many changes to this behavior.

Comment (Vahid1919) [reply packages/components/src/components/carousel/carousel.ts:460]: @karlbaumhauer These are two different behaviours. SlidesPerPage determines the number of slides visible on the screen at the same time. SlidesPerMove determines the amount of slides a carousel does per click.

I still have to closely test how these changes affect the behaviour but a lot of these tests are failing at moment so they should be resolved first.

Comment (karlbaumhauer) [reply packages/components/src/components/carousel/carousel.ts:460]: I understand the difference but I am just not sure with what we ended up in the last of the 100 dicussions on how we want to build it... ;-)

Would be awesome if you can have a closer look into it.

Comment (StefanCikarevic) [reply packages/components/src/components/carousel/carousel.ts:460]: @karlbaumhauer 
I updated the dot navigation logic by replacing slidesPerPage with slidesPerMove to correctly align navigation when slidesPerPage is greater than 1.

When slidesPerPage was greater than 1, clicking on a dot caused the carousel to jump to an incorrect slide. This happened because the dot navigation used slidesPerPage in the calculation, leading to unexpected results, like skipping slides or misaligned slide positions.

To fix this, I replaced slidesPerPage with slidesPerMove in the dot navigation calculations. Now, each dot click targets index * slidesPerMove, ensuring that the carousel accurately aligns with the intended set of slides.

Ticket: https://github.com/solid-design-system/solid/issues/1398

Comment (karlbaumhauer) [reply packages/components/src/components/carousel/carousel.ts:460]: ah ok. Thx for adding context.

**Review by Vahid1919 — APPROVED** [review]

**Comment by StefanCikarevic** [comment]
> @StefanCikarevic could you please add a test for this fix? Thank you

Since there’s no code change, only a parameter adjustment, I’d like to clarify, when you mention testing, does this mean we need to create a new story when slidesPerPage is greater than 1 and slidesPerMove is set?

**Comment by Vahid1919** [comment]
> > @StefanCikarevic could you please add a test for this fix? Thank you
> 
> Since there’s no code change, only a parameter adjustment, I’d like to clarify, when you mention testing, does this mean we need to create a new story when slidesPerPage is greater than 1 and slidesPerMove is set?

@StefanCikarevic To clarify, I believe a test that checks whether clicking a dot will navigate to the appropriate slide is sufficient here.

**Comment by karlbaumhauer** [comment]
> @karlbaumhauer Hello, is there anything else that needs to be done, or should I wait for the review to see the next steps?

@StefanCikarevic I second what @Vahid1919 is [suggesting](https://github.com/solid-design-system/solid/pull/1584#issuecomment-2441599439). 
Other than that, you just wait for the review to be done. In this case, @smfonseca requested a test and I would wait for his final review to merge the changes.

**Review by smfonseca — APPROVED** [review]

**Review by karlbaumhauer — APPROVED** [review]
