### PR TITLE
fix: 🤔 tabs do not grow with longer tab titles 

### LINKED ISSUE #901: fix: 🤔 tabs do not grow with longer tab titles
## Current behavior
When an sd-tab has a longer title than ~10 characters the text will overflow the tab size.
Bildschirmfoto 2024-04-02 um 08 15 15
For the part "base" there is a width of w-20 fixed. I suppose this should rather be min-width.

## Expected behavior
The tab width grows with longer tab titles.

## Steps to reproduce
Use a longer tab title in storybook.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:
Closes #901

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/tab/tab.ts [hunk 1]
```diff
@@ -74,7 +74,7 @@ export default class SdTab extends SolidElement {
       <div
         part="base"
         class=${cx(
-          'inline-flex gap-2 w-20 h-12 px-3 leading-none items-center justify-center whitespace-nowrap select-none cursor-pointer hover:bg-neutral-200 group relative focus-visible:focus-outline outline-2 !-outline-offset-2',
+          'inline-flex gap-2 min-w-min h-12 px-3 leading-none items-center justify-center whitespace-nowrap select-none cursor-pointer hover:bg-neutral-200 group relative focus-visible:focus-outline outline-2 !-outline-offset-2',
```
Comment (yoezlem) [inline packages/components/src/components/tab/tab.ts:77]: Is that really correct? min-w-max seems for me more corrector 🤔

**Comment by van-nguyen-ht** [comment]
Hi @Vahid1919 I left you some comments, here's the references 

Screenshot 2024-04-03 at 13 22 42

https://github.com/solid-design-system/solid/assets/118520877/acd82f22-35cb-4748-b585-ee6a8c25f0db

@karlbaumhauer can I leave these materials here and delete when Vahid is done?

File: packages/components/src/components/tab/tab.ts [hunk 2]
```diff
@@ -74,7 +74,7 @@ export default class SdTab extends SolidElement {
       <div
```
Comment (karlbaumhauer) [inline packages/components/src/components/tab/tab.ts:74]: @Vahid1919 If I look at the diff in chromatic, it already changes the size of the tab even though you did not change the length of the lable.

Comment (Vahid1919) [reply packages/components/src/components/tab/tab.ts:74]: @karlbaumhauer yes, that's because I set an explicit width for the tab before. I now realised that does not make sense since the width of the tab should be determined by the width of the text inside. This new width is based on the size of the text alone.

**Comment by van-nguyen-ht** [comment]
@Vahid1919 I can't add a photo in Chromatic so here's a screenshot of the No Line story for sd-tab-group
Screenshot 2024-04-08 at 15 49 34

**Review by karlbaumhauer — APPROVED** [review]
LGTM from development side.

File: packages/components/src/components/tab/tab.ts [hunk 3]
```diff
@@ -111,6 +111,12 @@ export default class SdTab extends SolidElement {
         border-bottom: none;
         border-radius: 4px 4px 0 0;
       }
+
+      .tab--bottom-border::before {
+        content: '';
+        @apply absolute w-full bottom-0 border-b border-neutral-400 invisible hover:visible;
+        height: 1px;
+      }
```
Comment (mariohamann) [inline packages/components/src/components/tab/tab.ts:119]: Hmm. Usually we would create the element as an own DOM element via JS here. What do you think?

**Review by yoezlem — APPROVED** [review]

**Comment by mariohamann** [comment]
@coraliefeil @Vahid1919 @van-nguyen-ht Is there anything blocking left?

**Comment by Vahid1919** [comment]
@mariohamann I just made the update from your review yesterday, which added a new screenshot for the parts story. 
Waiting for approval from @solid-design-system/design

**Review by mariohamann — APPROVED** [review]
