### PR TITLE
fix: 🤔 sd-carousel - numbered variant - show total clicks

### LINKED ISSUE #1191: fix: 🤔 sd-carousel - numbered variant - show total clicks
## Current behavior

For multiple slides per view:

The numbered variant does not show the total amount of clicks on the right: < 1 / 10 > (Immediate fix needed!)

## Expected behavior

The numbered variant shows the total amount of clicks on the right: < 1 / 10 >

Image

## Steps to reproduce

https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-carousel--default&args=variant-attr:10;slides-per-page-attr:2;slides-per-move-attr:1&globals=outline:!true

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:

Closes  #1191. Updating scrolling logic to ensure that the page number calculation is accurate no matter the divisibility of slides-per-page and slides-per-move. 

## Definition of Reviewable:

- [x] E2E tests (features, a11y, bug fixes) are created/updated
- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/carousel/carousel.ts
Comment (karlbaumhauer) [inline packages/components/src/components/carousel/carousel.ts:1]: @Vahid1919 are you sure this works as expected? I was able to configure some strange behavior again: 
image
IMO, no matter what we configure, it should never be 5 out of 4 right? I also tried to play around with your note you added but even when taking care on the numbers being divisible, I still hade 4 out of 3 clicks... :/

File: packages/components/src/components/carousel/carousel.ts [hunk 1]
```diff
@@ -84,6 +84,12 @@ export default class SdCarousel extends SolidElement {
    */
```
Comment (karlbaumhauer) [inline packages/components/src/components/carousel/carousel.ts:84]: unfortunately I cannot tag line 56 here but I found a strange behavior in Storybook on the variant property: 
image
shouldn't this be a string property instead of number? maybe the term `number` is reserved here... :/

**Review by karlbaumhauer — CHANGES_REQUESTED** [review]

File: packages/components/src/components/carousel/carousel.ts (hunk 1 above)
Comment (Vahid1919) [reply packages/components/src/components/carousel/carousel.ts:84]: I accidentally introduced a bug when I was cleaning up my code. This should be working now.

File: packages/components/src/components/carousel/carousel.ts
Comment (karlbaumhauer) [reply packages/components/src/components/carousel/carousel.ts:1]: this works now.

File: packages/components/src/components/carousel/carousel.ts (hunk 1 above)
Comment (karlbaumhauer) [reply packages/components/src/components/carousel/carousel.ts:84]: I think youre comment was towards my other conversation above right?

I will open up a new bug ticket as I found something else.

**Review by karlbaumhauer — APPROVED** [review]
approved from documentation perspective

**Comment by coraliefeil** [comment]
Approved

**Review by yoezlem — APPROVED** [review]

File: packages/components/src/components/carousel/carousel.ts [hunk 2]
```diff
@@ -342,7 +373,11 @@ export default class SdCarousel extends SolidElement {
       canSnap = Math.abs(previousIndex - this.slidesPerMove) % this.slidesPerMove === 0;
     }
 
-    this.goToSlide(previousIndex, behavior);
+    if (this.currentPage - 1 === 0 && this.loop) {
+      this.goToSlide(this.activeSlide - this.slidesPerPage, behavior);
+    } else {
+      this.goToSlide(previousIndex, behavior);
+    }
```
Comment (mariohamann) [inline packages/components/src/components/carousel/carousel.ts:380]: <video src="https://github.com/user-attachments/assets/cf0a48bf-02e1-4a04-bf46-1ddea036405e"></video>

This behaviour feels wrong.
- 5 slides, 2 per move, 2 per page
- Current: [4 5] → [3 4] → [1 2]
- Should: [4 5] → [2 3] → [1 2]

In the initial ticket ti says "it should always move the amount of slides per page as described if possible" – which would be currently violated.

**Review by mariohamann — CHANGES_REQUESTED** [review]

File: packages/components/src/components/carousel/carousel.stories.ts
[the remark this answers is not in the document]
Comment (mariohamann) [reply packages/components/src/components/carousel/carousel.stories.ts:1]: And sometimes Slide 2. On Safari.

**Comment by Vahid1919** [comment]
Local tests: 
image

**Review by mariohamann — APPROVED** [review]
