### PR TITLE
fix: make expandable inverted fit to theme

### LINKED ISSUE #1299: fix: 🤔 make sd-expandable inverted fit to theming
## Current behavior

CleanShot 2024-08-19 at 11 44 24@2x

CleanShot 2024-08-19 at 11 45 08@2x

Here we should have the colors only as fallback.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by paulovareiro29**
Steps for testing:
- Go to the `sd-expandable` inverted story.
- Override on the DOM the following variables: `--gradient-color-start` and `--gradient-color-end` to `rgba(45, 157, 0, 0)` and `rgba(45, 157, 0, 1)` respectively.
- On production, the gradient doesn't change color. On this PR it does.

## Description:
Closes #1299 

## Definition of Reviewable:
- [x] relevant tickets are linked

### CODE REVIEW

File: packages/components/src/components/expandable/expandable.ts [hunk 1]
```diff
@@ -232,11 +232,13 @@ export default class SdExpandable extends SolidElement {
         background: linear-gradient(180deg, var(--gradient));
       }
 
+      :host([inverted]) {
+        --gradient-color-start: rgba(0, 53, 142, 0);
```
Comment (smfonseca) [inline packages/components/src/components/expandable/expandable.ts]: Maybe we could place the rgb value in a css variable to identify that this is the color primary. What do you think?
