### PR TITLE
fix: sd-drawer a11y reaudit

### LINKED ISSUE #2074: feat[dev]: ✨ implement A11y Re-Improvements to Drawer Template
## Description
This tasks describes the Figma implementation for: #2048 

This task describes the Storybook implementation for the drawer template as part of the A11y re-improvements outlined in Epic #2048.

A11y improvements for drawer template can be found here: [drawer template Notes](https://www.notion.so/matuzo/Drawer-1baf3f6e1bc0814caca9c5e8b4c72960).

------------------------------------------

## Notes
- The accessible names of the navigations can be improved. “Primary” instead of “nav-level-one”, etc.

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by paulovareiro29**
## Description:

Closes #2074 

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked

### CODE REVIEW

**Review by auroraVasconcelos — APPROVED** [review]

File: packages/components/src/components/drawer/drawer.ts [hunk 1]
```diff
@@ -359,7 +357,12 @@ export default class SdDrawer extends SolidElement {
                 class="absolute top-2 right-2"
                 ><sd-icon label=${this.localize.term('close')} name="close" library="system"></sd-icon
               ></sd-button>`}
-          <div part="body" class="flex-auto block px-4" tabindex="0">
+          <div
+            part="body"
+            class="flex-auto block px-4 focus-visible:focus-outline !-outline-offset-2"
+            aria-label=${this.label}
```
Comment (smfonseca) [inline packages/components/src/components/drawer/drawer.ts:363]: I'm not sure if we should use the label here again. 

In the [template](https://solid-design-system.github.io/solid/fix_sd-drawer-a11y-reaudit/?path=/docs/templates-drawer--docs) the label is `first drawer`. When you first open the drawer it announces `first drawer, web dialogue` and then you tab into the body and it's `first drawer, group`. Can be slightly confusing. What do you think of introducing a `bodyLabel` or similar? 
This can also be a bad example and we don't need to change anything. What do you think?

Comment (paulovareiro29) [reply packages/components/src/components/drawer/drawer.ts:363]: Maybe we can just remove the `aria-label`. This way it will announce `group, Primary Secondary`.
`Primary` & `Secondary` are the labels of the `nav`s' inside

Comment (smfonseca) [reply packages/components/src/components/drawer/drawer.ts]: Yes, I think that could work

**Review by smfonseca — APPROVED** [review]
